version: "3.7"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev
    container_name: vue-app



